# Workflow to build and deploy my site to GitHub Pages
name: Deploy my site to shahnawaz-pabon.github.io

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as the part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE so that the job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      # Install packages
      - name: Install packages 🔨 
        run: npm install

      # Clean caches
      - name: Clean caches 🎡 
        run: npm run clean

      # This example project is built using npm and outputs the result to the 'public' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      - name: Build 🔧
        run: npm run build:pp

      # Deploy to master
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          # The branch the action should deploy to
          branch: master
          # The folder the action should deploy
          folder: public